### ISSUE TITLE
4 radarrs?

### ISSUE THREAD

**Issue by danjames92** [Sperryfreak01/RadarrSync#1]
Can you use more than 2?

**Comment by Sperryfreak01** [comment]
Today it's limited to two servers, and will only sync profile '5' (ultrahd). 

Wouldn't be hard to expand it to more servers though.  Can you give me your use case so I can think about it.

**Comment by Sperryfreak01** [comment]
Actually in a crude way it does support one-to-many.  Just create multiple copies of the script in different folders, only one config.txt file per folder, and run those but it is hard coded to ultrahd right now.

**Comment by hjone72** [comment]
@danjames92, could you please test https://github.com/hjone72/RadarrSync/tree/MultiServer before I make a pull request?

**Comment by EnorMOZ** [comment]
@hjone72 I just tried and noticed 2 things... The path mappings don't see to be working. It seems like it is pulling everything. Also it did not like chinese characters... 
ie:
`/mnt/unionfs/Media/Kids Movies` to `/mnt/unionfs/Media/Kids Movies4k`

`UnicodeEncodeError: 'ascii' codec can't encode character u'\xb3' in position 31: ordinal not in range(128)`

**Comment by hjone72** [comment]
@EnorMOZ would you be able to post your Output.txt please? Feel free to remove any sensitive data.

**Comment by hjone72** [comment]
@EnorMOZ I've done a bit of testing using the following characters `東京ゴッドファーザーズ`. I can't seem to fault the program anymore.

The code I added was Python2 not 3. Python3 handles these characters much better. I've updated the code to work with Python3. Grab the latest commit and test again please?

**Comment by EnorMOZ** [comment]
@hjone72 

Example output: Clearly not a "kids movie" :)
`2018-03-31 05:27:02,130 [MainThread  ] [INFO ]  adding 300: Rise of an Empire to Radarr 4k server`

It is almost like it is ignoring the config basepath and using the first one in radarr which is set to `/mnt/unionfs/Media/Movies`.

Trying to sync the movies from `master` which are set to profile `4` from the basepath of `/mnt/unionfs/Media/Kids\ Movies` to `Radarr_4k` setting it to profile `5` to the basepath of `/mnt/unionfs/Media/Kids\ Movies4k`

Example config file. 
`[RadarrMaster]
url = http://127.0.0.1:7878
key = XXXXX
basepath = /mnt/unionfs/Media/Kids\ Movies

[SyncServers]
; Ensure the servers start with 'Radarr_'
[Radarr_4k]
url = http://127.0.0.1:7879
key = XXXXXXXX
newpath = /mnt/unionfs/Media/Kids\ Movies4k
;This is the profile ID the movie will be added to.
profileId = 5
; This is the profile ID the movie must have on the Master server.
profileIdMatch = 4`

**Comment by EnorMOZ** [comment]
@hjone72, Take a look at my fork. It is my attempt to try to sling python. The path part seems to be working but images are not working properly.

**Comment by lcasey001** [comment]
https://github.com/hjone72/RadarrSync/tree/MultiServer works great now.

**Comment by Sperryfreak01** [comment]
fixed by #7, multiple servers are now supported.  No restriction on the  number or naming of server, as long as the primary server is named 'radarr' or 'default'
