### ISSUE TITLE
Search for movies after sync

### ISSUE THREAD

**Issue by mrnoisytiger** [Sperryfreak01/RadarrSync#10]
It would be great if Radarr could search for the added movies after syncing, just like how Ombi does it.

**Comment by Sperryfreak01** [comment]
it should do that now....are you seeing anything in the logs of your target server (formally Radarr4K but now it supports more than one server #6 ).

**Comment by Sperryfreak01** [comment]
did this resolve when we fixed #9

**Comment by mrnoisytiger** [comment]
Yep! Works perfectly! Thanks!
