### ISSUE TITLE
subsequent runs do nothing

### ISSUE THREAD

**Issue by madbuda** [Sperryfreak01/RadarrSync#27]
**Describe the bug**
subsequent runs of sync does nothing if you change to a different radarr instance or if there is an error

**To Reproduce**
run sync, let it complete

Remove all movies from 4k radarr instance

run sync again, it just ends with no error or msg

**Expected behavior**
syncs all content again

**Configuration**
[Radarr]
url = http://xxxxxx:7878
key = xxxxxx

[Radarr4k]
url = http://xxxxx:7874
key = xxxxx
profile = Ultra-HD

[General]

**Logs**
empty

**Comment by lludlow** [comment]
I reply, cleaning up my open issues
