### ISSUE TITLE
Script crashes on invalid Profile ID

### ISSUE THREAD

**Issue by mattmac24** [Sperryfreak01/RadarrSync#5]
Hi,

I am getting a python error when I run this script(and other forks of this script). But perhaps this may be to do with my python environment? I have not changed anything other than the profile id from 5 to 7 which is hardcoded in the script.

```
Traceback (most recent call last):
  File "RadarrSync.py", line 93, in <module>
    searchid.append(int(r.json()['id']))
TypeError: list indices must be integers or slices, not str
```

I am running the script with
`python3 RadarrSync.py
`

Can I please have some help to get this running?

Thanks in advance :)

**Comment by Xert0** [comment]
is it because  in `searchid.append(int(r.json()['id']))` it is put as ['id'] rather than [id]?

**Comment by mattmac24** [comment]
I just tried it as [id] and got the same error:

`
Traceback (most recent call last):
  File "RadarrSync.py", line 93, in <module>
    searchid.append(int(r.json()[id]))
TypeError: list indices must be integers or slices, not builtin_function_or_method
`

I do not understand what is happening, I have tried this on two computers now and received this error. Others seem to be able to run the code without any error so i'm confused.

**Comment by mattmac24** [comment]
Worked it out. This is the error you get when the quality profile of your server is wrong and doesn't exist.

**Comment by Sperryfreak01** [comment]
Reopening this as an enhancement.  I found a way to support profile verification and also allow users to enter the profile ID number or just the profile name as shown in the Radarr web interface.  Working on the update now.

**Comment by mattmac24** [comment]
Great to hear! The OCD in me requires that I delete all of the default profiles and create my own new one. Took me more then it should have to find out the correct profile ID to use.

**Comment by Sperryfreak01** [comment]
This is fixed but I need to update documentation to make it more clear how to use it.
