### ISSUE TITLE
Script Ran but not syncing

### ISSUE THREAD

**Issue by mrnoisytiger** [Sperryfreak01/RadarrSync#9]
Hey man! I found your script while browsing Reddit for a solution two keeping my 2 Radarr instances in sync.

Right now, I have the script set up and the config info set correctly. However, when I try to run the script, the script errors out with:

```
Traceback (most recent call last): File "RadarrSync.py", line 54, in <module> radarr4k_url = ConfigSectionMap("Radarr4k")['url'] File "RadarrSync.py", line 28, in ConfigSectionMap options = Config.options(section) File "/usr/lib/python3.5/configparser.py", line 674, in options raise NoSectionError(section) from None configparser.NoSectionError: No section: 'Radarr4k'
```

I narrowed it down to the DEV=True line. When I switched it to false and ran the script, the script pauses for about a second, and then ends. there are no errors or logs or anything.

I'm running it on Ubuntu 16.04 with Python 3.5. I downloaded the GitHub repo as a zip and just unzipped it. I ran `pip3 install -r requirements.txt` before first running the script.

Any help on getting it working would be super duper appreciated!

**Comment by mrnoisytiger** [comment]
Updating to the latest commit solved the issue!

**Comment by Sperryfreak01** [comment]
Two things.

* DEV mode shouldnt have been enabled, that was bad luck on your part.  I fixed this after you messaged me [https://github.com/Sperryfreak01/RadarrSync/commit/fbdd5b95dce1b90cf723a27d8294b382af08c3fc](url)
* Can you post your Config.txt file, make sure to remove personal info before you do.  I think it might be that the heading of your 4K section was changed from [Radarr4k} to something else.

**Comment by Sperryfreak01** [comment]
you beat me to it, guess there was something else besides the DEV mode that changed.  I did a lot of refactoring in the two hours the DEV mode issue was up there.

**Comment by mrnoisytiger** [comment]
My config.txt looks like this:

```
[Radarr]
url = http://127.0.0.1:7878
key = 7c6ef2bca5174f9c8ad203927b5766d1


[Radarr4k]
url = http://127.0.0.1:7879
key = 7c6ef2bca5174f9c8ad203927b5766d1
profile = 5
```

It appears that I'm still having a bit of trouble with the sync. No matter whether I set `profile=5` or `profile=6`, I still can't seem to get it to sync by running `python3 RadarrSync.py`

My output looks like:

```
2018-09-03 20:02:25,201 [MainThread  ] [DEBUG]  Starting new HTTP connection (1): 127.0.0.1
2018-09-03 20:02:25,283 [MainThread  ] [DEBUG]  http://127.0.0.1:7878 "GET /api/movie?apikey=7c6ef2bca5174f9c8ad203927b5766d1 HTTP/1.1" 200 None
2018-09-03 20:02:25,309 [MainThread  ] [DEBUG]  syncing to Radarr4k
2018-09-03 20:02:25,310 [MainThread  ] [DEBUG]  Starting new HTTP connection (1): 127.0.0.1
2018-09-03 20:02:25,386 [MainThread  ] [DEBUG]  http://127.0.0.1:7879 "GET /api/movie?apikey=7c6ef2bca5174f9c8ad203927b5766d1 HTTP/1.1" 200 None
```

I know the config URL's are correct since `curl`ing them gives the expected output.

**Comment by mrnoisytiger** [comment]
Also, the API keys are indeed the same between the two instances.

**Comment by mrnoisytiger** [comment]
As well, during my testing, I've been trying to sync from 4K to 1080p. However, in production, I would actually like it the other way around, so I don't have to wait for a cron tick for a search.

**Comment by Sperryfreak01** [comment]
My api keys are the same as well, a convient by product of cloning the docker container.  Did you copy a docker container?  If so does your 4K server still have all the same movies in the DB as your original install?

**Comment by mrnoisytiger** [comment]
Instead of cloning the docker container (`linuxserver.io`), I created a new one and simply make a duplicate of the config directory.

As a result, all the movies are copied over but after a rescan of each one's individual directory, the appropriate ones are missing and have been searched for. Everything is good on that end.

However, now, I added a movie to the 4K one and want to push it over to the 1080p one but it's not going through. :cry:

**Comment by mrnoisytiger** [comment]
Not the exactly familiar with Python but I don't mind at all! Just tell me what to change! 😄

**Comment by Sperryfreak01** [comment]
BTW, if you want to sync the opposite way you could...though not officially supported just reverse flip the ports.  It still wont be bidirectional though.

**Comment by mrnoisytiger** [comment]
🤣 Fair point. Didn't need it to be bidirectional at all! 😆 Was just for testing purposes!

**Comment by Sperryfreak01** [comment]
you can open the script in notepad or a text editor of your choice

Replace the following block
```
    for movie in radarrMovies.json():
        if movie['profileId'] == int(ConfigSectionMap(server)['profile']):
            if movie['tmdbId'] not in movieIds_to_syncserver:
                logging.debug('title: {0}'.format(movie['title']))
                logging.debug('qualityProfileId: {0}'.format(movie['qualityProfileId']))
                logging.debug('titleSlug: {0}'.format(movie['titleSlug']))
                images = movie['images']
                for image in images:
                    image['url'] = '{0}{1}'.format(radarr_url, image['url'])
                    logging.debug(image['url'])
                logging.debug('tmdbId: {0}'.format(movie['tmdbId']))
                logging.debug('path: {0}'.format(movie['path']))
                logging.debug('monitored: {0}'.format(movie['monitored']))

                payload = {'title': movie['title'],
                           'qualityProfileId': movie['qualityProfileId'],
                           'titleSlug': movie['titleSlug'],
                           'tmdbId': movie['tmdbId'],
                           'path': movie['path'],
                           'monitored': movie['monitored'],
                           'images': images,
                           'profileId': movie['profileId'],
                           'minimumAvailability': 'released'
                           }

                r = session.post('{0}/api/movie?apikey={1}'.format(SyncServer_url, SyncServer_key), data=json.dumps(payload))
                searchid.append(int(r.json()['id']))
                logger.info('adding {0} to {1} server'.format(movie['title'], server))
            else:
                logging.debug('{0} already in {1} library'.format(movie['title'], server))
```
with 

```
    for movie in radarrMovies.json():
        if movie['profileId'] == int(ConfigSectionMap(server)['profile']):
            if movie['tmdbId'] not in movieIds_to_syncserver:
                logging.debug('title: {0}'.format(movie['title']))
                logging.debug('qualityProfileId: {0}'.format(movie['qualityProfileId']))
                logging.debug('titleSlug: {0}'.format(movie['titleSlug']))
                images = movie['images']
                for image in images:
                    image['url'] = '{0}{1}'.format(radarr_url, image['url'])
                    logging.debug(image['url'])
                logging.debug('tmdbId: {0}'.format(movie['tmdbId']))
                logging.debug('path: {0}'.format(movie['path']))
                logging.debug('monitored: {0}'.format(movie['monitored']))

                payload = {'title': movie['title'],
                           'qualityProfileId': movie['qualityProfileId'],
                           'titleSlug': movie['titleSlug'],
                           'tmdbId': movie['tmdbId'],
                           'path': movie['path'],
                           'monitored': movie['monitored'],
                           'images': images,
                           'profileId': movie['profileId'],
                           'minimumAvailability': 'released'
                           }

                r = session.post('{0}/api/movie?apikey={1}'.format(SyncServer_url, SyncServer_key), data=json.dumps(payload))
                searchid.append(int(r.json()['id']))
                logger.info('adding {0} to {1} server'.format(movie['title'], server))
            else:
                logging.debug('{0} already in {1} library'.format(movie['title'], server))
        else:
            logging.debug('Skipping {0}, wanted profile: {1} found profile: {2}'.format(movie['title'],
                                                                                        movie['profileId'],
                                                                                        int(ConfigSectionMap(server)['profile'])
                                                                                        ))

```

**Comment by mrnoisytiger** [comment]
Here's a block of relevant output!

```
2018-09-03 20:32:37,409 [MainThread  ] [DEBUG]  Skipping A Ghost Story, wanted profile: 8 found profile: 5
2018-09-03 20:32:37,409 [MainThread  ] [DEBUG]  Skipping Mamma Mia!, wanted profile: 8 found profile: 5
2018-09-03 20:32:37,409 [MainThread  ] [DEBUG]  Skipping Mamma Mia! Here We Go Again, wanted profile: 8 found profile: 5
2018-09-03 20:32:37,409 [MainThread  ] [DEBUG]  Skipping Atomic Blonde, wanted profile: 7 found profile: 5
2018-09-03 20:32:37,409 [MainThread  ] [DEBUG]  Skipping Ant-Man, wanted profile: 8 found profile: 5
2018-09-03 20:32:37,409 [MainThread  ] [DEBUG]  Skipping Princess Mononoke, wanted profile: 7 found profile: 5
```

The one I'm having an issue with not syncing over is Ant-Man!

**Comment by mrnoisytiger** [comment]
I'm going to try changing the config to `profile=8` and see what happens!

**Comment by mrnoisytiger** [comment]
**Looks like that did it!** Apparently, I was not using the needed profile number for it to sync over...

**Comment by Sperryfreak01** [comment]
yeah, its because the wrong profile.  by default profile 8 is... nothing.  Hmm at least on mines its nothing.  

if you go to http://127.0.0.1:7878/settings/profiles what are your profiles?  It counts left to right row by row.  I only have 7 profiles.

**Comment by mrnoisytiger** [comment]
Ah I added a custom profile for RadarrSync on both of my installations! I didn't realize that's how the profile setting worked! 😿

**Comment by mrnoisytiger** [comment]
**Thanks for all your help man!!!!**

**Comment by Sperryfreak01** [comment]
yeah, there is no way for the script to get the profiles today.  The radarr API doesnt support it.  Glad you got it working, so was your 4K profile the 4th profile on the second row?

**Comment by mrnoisytiger** [comment]
Yep exactly! 

[Imgur](https://i.imgur.com/rx92Gtk.png)

I made a custom profile for RadarrSync for internal naming consistency. Didn't want the 1080p instance to be called UHD, but that's just because I'm a tad OCD with naming.

**Comment by Sperryfreak01** [comment]
No justification needed, glad its working.
